### PR TITLE
Change carousel banner images

### PR DESCRIPTION
**Pull request by russdaygh**

### CODE REVIEW

**Review by dynamictulip — APPROVED** [review]
Nice one, these are great!
Do we have any higher res images for larger screens? I noticed that it's quite pixelated on my desktop pc. If not then no worries, the old ones were pixelated too and this is an improvement

**Comment by CarlSargunar** [comment]
Thanks Russ - I think you saved me a job, I had this on my todo list?

Looks good though!

**Comment by russdaygh** [comment]
> Nice one, these are great! Do we have any higher res images for larger screens? I noticed that it's quite pixelated on my desktop pc. If not then no worries, the old ones were pixelated too and this is an improvement

These are the highest res we have for now. We can make an effort to get better photos this year.

**Comment by russdaygh** [comment]
> Thanks Russ - I think you saved me a job, I had this on my todo list?
> 
> Looks good though!

Yeh, we got a bit carried away at the end of the workshop.

**Comment by slang25** [comment]
I have some higher res versions of these, I'll have a play later using srcset so we have different images for different devices/bandwidths, cause higher res would be nice, but not what you want on mobile.

**Pull request merged**
